SRCS+=\
	$(REL)NTuple.cpp\
	$(REL)NTuples.cpp\
	$(REL)NTuplesBuilder.cpp\
	$(REL)NTupleUtils.cpp\

REL := NTuple/eval/
include $(REL)Makefile

REL := NTuple/expanders/
include $(REL)Makefile

REL := NTuple/factories/
include $(REL)Makefile
